apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-sample
  template:
    metadata:
      labels:
        app: tomcat-sample
    spec:
      containers:
      - name: tomcat-sample
        image: ${IMAGE_URI}
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-1
  namespace: default
spec:
  selector:
    app: tomcat-sample
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:  
  name: sample-service-2
  namespace: default
spec:
  selector:
    app: tomcat-sample
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  